theme: jekyll-theme-hacker
title: "Bruno Panuto: Software Developer"
collections:
  - projects
defaults:
  -
    scope:
      path: ""
      type: default
    values:
      layout: default
      author: "Bruno Panuto"